#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CloudClubv1._2_.Droid.Resource", IsApplication=true)]

namespace CloudClubv1._2_.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Alien_Character = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Baby_Character = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Burger_Character = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Cat_Character = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Cloud = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int cloudIcon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Cookie_Character = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Demon_Character = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Devil_Character = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Dog_Character = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Dolphin_Character = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int DropletFull_WhiteB = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Eek_Character = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Ghost_Character = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Headphones_Character = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Horse_Character = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Icecream_Character = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int icon = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Laugh_Character = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Medal_WhiteB = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Middlefinger_Character = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int monoandroidsplash = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Mouse_Character = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int News_Profile = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int page2Tutorial = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int page3Tutorial = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int page4Tutorial = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int Pumpkin_Character = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int Santa_Character = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int Settings_Top = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int Shit_Character = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int Skull_Character = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int Sleeping_Character = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int Spy_Character = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int Star_Empty = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int Star_Gold = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int Star_Gray = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int Star_Green = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int Star_LightBlue = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int Star_Pink = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int Star_Purple = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int Star_Red = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int Teethsmile_Character = 2130837546;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f030000
			public const int Mono_Android_Theme_Splash = 2130903040;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
