#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CloudClubv1._2_.Droid.Resource", IsApplication=true)]

namespace CloudClubv1._2_.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Gcm.Client.Resource.String.library_name = global::CloudClubv1._2_.Droid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AA1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int AA10 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int AA11 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int AA12 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int AA13 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int AA14 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int AA15 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int AA16 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int AA17 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int AA18 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int AA19 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int AA2 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int AA20 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int AA21 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int AA22 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int AA23 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int AA24 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int AA25 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int AA26 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int AA27 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int AA28 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int AA29 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int AA3 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int AA30 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int AA31 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int AA32 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int AA33 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int AA34 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int AA35 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int AA36 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int AA37 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int AA38 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int AA39 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int AA4 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int AA40 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int AA5 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int AA6 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int AA7 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int AA8 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int AA9 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int AE1 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int AF1 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int AF10 = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int AF11 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int AF12 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int AF13 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int AF14 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int AF15 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int AF16 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int AF17 = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int AF18 = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int AF19 = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int AF2 = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int AF20 = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int AF21 = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int AF22 = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int AF23 = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int AF24 = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int AF25 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int AF26 = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int AF27 = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int AF28 = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int AF29 = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int AF3 = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int AF30 = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int AF31 = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int AF32 = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int AF33 = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int AF34 = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int AF35 = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int AF36 = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int AF37 = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int AF38 = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int AF39 = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int AF4 = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int AF40 = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int AF5 = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int AF6 = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int AF7 = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int AF8 = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int AF9 = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int Alien_Character = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int AN1 = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int AN10 = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int AN11 = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int AN12 = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int AN13 = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int AN14 = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int AN15 = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int AN16 = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int AN17 = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int AN18 = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int AN19 = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int AN2 = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int AN20 = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int AN21 = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int AN22 = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int AN23 = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int AN24 = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int AN25 = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int AN26 = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int AN27 = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int AN28 = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int AN29 = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int AN3 = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int AN30 = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int AN31 = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int AN32 = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int AN33 = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int AN35 = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int AN36 = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int AN37 = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int AN38 = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int AN4 = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int AN40 = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int AN5 = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int AN6 = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int AN7 = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int AN8 = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int AN9 = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int Baby_Character = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int Burger_Character = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public const int Cat_Character = 2130837626;
			
			// aapt resource value: 0x7f02007b
			public const int Cloud = 2130837627;
			
			// aapt resource value: 0x7f02007c
			public const int cloudIcon = 2130837628;
			
			// aapt resource value: 0x7f02007d
			public const int Club_News = 2130837629;
			
			// aapt resource value: 0x7f02007e
			public const int ClubSearch_TabView = 2130837630;
			
			// aapt resource value: 0x7f02007f
			public const int Cookie_Character = 2130837631;
			
			// aapt resource value: 0x7f020080
			public const int Demon_Character = 2130837632;
			
			// aapt resource value: 0x7f020081
			public const int Devil_Character = 2130837633;
			
			// aapt resource value: 0x7f020082
			public const int Dog_Character = 2130837634;
			
			// aapt resource value: 0x7f020083
			public const int Dolphin_Character = 2130837635;
			
			// aapt resource value: 0x7f020084
			public const int DropletFull_WhiteB = 2130837636;
			
			// aapt resource value: 0x7f020085
			public const int Eek_Character = 2130837637;
			
			// aapt resource value: 0x7f020086
			public const int Friends_Profile1 = 2130837638;
			
			// aapt resource value: 0x7f020087
			public const int Ghost_Character = 2130837639;
			
			// aapt resource value: 0x7f020088
			public const int Headphones_Character = 2130837640;
			
			// aapt resource value: 0x7f020089
			public const int Horse_Character = 2130837641;
			
			// aapt resource value: 0x7f02008a
			public const int Icecream_Character = 2130837642;
			
			// aapt resource value: 0x7f02008b
			public const int icon = 2130837643;
			
			// aapt resource value: 0x7f02008c
			public const int Laugh_Character = 2130837644;
			
			// aapt resource value: 0x7f02008d
			public const int Medal_WhiteB = 2130837645;
			
			// aapt resource value: 0x7f02008e
			public const int Middlefinger_Character = 2130837646;
			
			// aapt resource value: 0x7f02008f
			public const int Mouse_Character = 2130837647;
			
			// aapt resource value: 0x7f020090
			public const int MyClubs_TabView = 2130837648;
			
			// aapt resource value: 0x7f020091
			public const int News_Profile = 2130837649;
			
			// aapt resource value: 0x7f020092
			public const int News_Profile1 = 2130837650;
			
			// aapt resource value: 0x7f020093
			public const int page2Tutorial = 2130837651;
			
			// aapt resource value: 0x7f020094
			public const int page3Tutorial = 2130837652;
			
			// aapt resource value: 0x7f020095
			public const int page4Tutorial = 2130837653;
			
			// aapt resource value: 0x7f020096
			public const int Profile_TabView = 2130837654;
			
			// aapt resource value: 0x7f020097
			public const int Pumpkin_Character = 2130837655;
			
			// aapt resource value: 0x7f020098
			public const int Santa_Character = 2130837656;
			
			// aapt resource value: 0x7f020099
			public const int Settings_Top = 2130837657;
			
			// aapt resource value: 0x7f02009a
			public const int Shit_Character = 2130837658;
			
			// aapt resource value: 0x7f02009b
			public const int Skull_Character = 2130837659;
			
			// aapt resource value: 0x7f02009c
			public const int Sleeping_Character = 2130837660;
			
			// aapt resource value: 0x7f02009d
			public const int Spy_Character = 2130837661;
			
			// aapt resource value: 0x7f02009e
			public const int Star_Empty = 2130837662;
			
			// aapt resource value: 0x7f02009f
			public const int Star_Gold = 2130837663;
			
			// aapt resource value: 0x7f0200a0
			public const int Star_Gray = 2130837664;
			
			// aapt resource value: 0x7f0200a1
			public const int Star_Green = 2130837665;
			
			// aapt resource value: 0x7f0200a2
			public const int Star_LightBlue = 2130837666;
			
			// aapt resource value: 0x7f0200a3
			public const int Star_Pink = 2130837667;
			
			// aapt resource value: 0x7f0200a4
			public const int Star_Purple = 2130837668;
			
			// aapt resource value: 0x7f0200a5
			public const int Star_Red = 2130837669;
			
			// aapt resource value: 0x7f0200a6
			public const int Teethsmile_Character = 2130837670;
			
			// aapt resource value: 0x7f0200a7
			public const int Tutorial_Competition = 2130837671;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int library_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
